# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156rRbdwTbntCLdp2qElV0RRv6uKStXn8
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("download.jpg")
cv2_imshow(rasm)

qoraoq= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(qoraoq)